In [9]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [10]:
df = pd.read_csv("C:\\Users\\Vijay\\Desktop\\dataset.csv")
df

,Class,nring,nrot,ndonr,naccr,dis1,dis2,dis3,0c,1c,...,MS,PSA,Sapc,Sanc,Sapcw,Sancw,Svpc,Svnc,Svpcw,Svncw
0,1,5,5,1,8,14.0728,19.9971,29.7056,23.2753,15.9603,...,388.7751,93.7600,483.5033,198.7825,50.4138,43.0631,261.6603,178.6998,29.0866,32.9824
1,1,7,8,5,17,18.3987,29.1307,41.9456,66.9766,42.1016,...,1078.3437,276.8944,1087.3566,283.6460,109.0626,76.9949,754.1281,467.3322,93.6200,112.7599
2,1,5,5,6,11,15.9217,21.4360,31.9111,28.3860,18.4278,...,431.6854,181.3898,487.8483,253.0542,68.0452,61.5911,266.2773,235.6881,37.6381,49.6918
3,1,4,3,2,5,13.0372,16.8927,24.0154,18.6899,12.3692,...,293.8360,78.8970,368.0259,154.2652,40.9066,41.4372,221.7073,148.8955,25.5404,30.2031
4,1,3,11,0,3,15.6200,21.8095,32.4662,22.3801,14.9939,...,423.9168,37.9313,577.2155,168.3255,59.2792,25.4594,291.2521,193.6013,31.7277,27.7454
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
749,-1,2,9,2,5,12.7882,19.4653,24.5601,19.2672,12.4003,...,339.0629,87.8772,486.6220,115.0808,49.1108,34.4332,267.9176,153.2767,30.8568,35.3643
750,-1,3,7,0,3,12.9131,17.1766,25.7497,18.7338,12.3750,...,363.4048,30.0842,479.8389,141.9631,45.6243,23.1197,238.2958,163.2771,22.5731,25.2704
751,-1,2,2,2,3,12.1659,13.8090,24.6997,11.3805,7.7540,...,213.6107,79.4822,306.1379,124.8699,53.1246,27.2107,118.8086,108.4076,19.8123,21.5416
752,-1,1,3,2,0,9.2957,10.9135,17.7013,7.2342,4.9319,...,160.7730,41.8416,255.5729,80.5598,32.1785,13.4743,93.5198,80.8540,11.4599,12.0897
753,-1,3,5,2,5,15.3819,18.5673,31.5799,17.4828,11.3094,...,305.9972,113.2147,381.2325,191.7601,51.6159,47.6664,195.9420,151.6053,27.8427,32.0934

In [11]:
target_columns = [ 'Class','Wmol','PSA','nring', 'nrot',  'ndonr', 'naccr', 'nhyd', 'ncarb', 'noxy', 'nnitro', 'nsulph', 'nhet', 'Shev', 'Scar','Shet', 'Shal', 'phi', 'Vmc', 'mcp', 'AS' ] 
X = df.drop(columns=target_columns) 
y = df[target_columns]

In [12]:
X

,dis1,dis2,dis3,0c,1c,2c,3cP,3cC,4cPC,3cCH,...,VS,MS,Sapc,Sanc,Sapcw,Sancw,Svpc,Svnc,Svpcw,Svncw
0,14.0728,19.9971,29.7056,23.2753,15.9603,14.5570,12.8918,2.3799,6.0177,0.0000,...,440.3601,388.7751,483.5033,198.7825,50.4138,43.0631,261.6603,178.6998,29.0866,32.9824
1,18.3987,29.1307,41.9456,66.9766,42.1016,40.5712,34.3946,8.2319,20.6087,0.0000,...,1221.4604,1078.3437,1087.3566,283.6460,109.0626,76.9949,754.1281,467.3322,93.6200,112.7599
2,15.9217,21.4360,31.9111,28.3860,18.4278,17.6913,16.2261,2.8918,8.2157,0.0000,...,501.9654,431.6854,487.8483,253.0542,68.0452,61.5911,266.2773,235.6881,37.6381,49.6918
3,13.0372,16.8927,24.0154,18.6899,12.3692,11.7933,10.9531,1.3724,3.6814,0.0000,...,370.6028,293.8360,368.0259,154.2652,40.9066,41.4372,221.7073,148.8955,25.5404,30.2031
4,15.6200,21.8095,32.4662,22.3801,14.9939,12.7462,11.0067,1.7513,4.6964,0.0000,...,484.8534,423.9168,577.2155,168.3255,59.2792,25.4594,291.2521,193.6013,31.7277,27.7454
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
749,12.7882,19.4653,24.5601,19.2672,12.4003,10.8161,8.7753,1.7138,4.3279,0.0000,...,421.1943,339.0629,486.6220,115.0808,49.1108,34.4332,267.9176,153.2767,30.8568,35.3643
750,12.9131,17.1766,25.7497,18.7338,12.3750,11.7762,8.8997,1.4704,2.6459,0.1667,...,401.5729,363.4048,479.8389,141.9631,45.6243,23.1197,238.2958,163.2771,22.5731,25.2704
751,12.1659,13.8090,24.6997,11.3805,7.7540,6.7370,5.2796,0.8952,1.7934,0.0000,...,227.2162,213.6107,306.1379,124.8699,53.1246,27.2107,118.8086,108.4076,19.8123,21.5416
752,9.2957,10.9135,17.7013,7.2342,4.9319,3.6463,2.6907,0.2041,0.4330,0.0000,...,174.3738,160.7730,255.5729,80.5598,32.1785,13.4743,93.5198,80.8540,11.4599,12.0897
753,15.3819,18.5673,31.5799,17.4828,11.3094,11.1489,8.5909,1.4981,3.5021,0.0000,...,347.5474,305.9972,381.2325,191.7601,51.6159,47.6664,195.9420,151.6053,27.8427,32.0934

In [13]:
y

,Class,Wmol,PSA,nring,nrot,ndonr,naccr,nhyd,ncarb,noxy,...,nsulph,nhet,Shev,Scar,Shet,Shal,phi,Vmc,mcp,AS
0,1,455.4634,93.7600,5,5,1,8,25,24,8,...,0,9,78.5000,17.0354,61.4646,0.0000,5.7732,2.0864,-4.3747,682.2858
1,1,1255.4322,276.8944,7,8,5,17,86,62,16,...,0,28,233.8333,-0.9527,234.7861,0.0000,21.4447,5.0382,-5.2925,1371.0026
2,1,543.5262,181.3898,5,5,6,11,29,27,11,...,0,12,109.4167,-7.0099,116.4265,0.0000,7.0384,2.2310,-5.0174,740.9025
3,1,360.4492,78.8970,4,3,2,5,28,21,5,...,0,5,65.1667,8.2800,56.8867,0.0000,4.2330,1.5117,-5.3573,522.2911
4,1,645.3180,37.9313,3,11,0,3,29,25,3,...,0,6,63.7400,31.1228,32.6172,4.5377,9.5127,2.3260,-5.0652,745.5410
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
749,-1,368.4722,87.8772,2,9,2,5,32,19,5,...,0,7,64.6667,8.4205,56.2462,0.0000,7.7320,1.9899,-4.3178,601.7028
750,-1,391.2932,30.0842,3,7,0,3,20,21,3,...,0,5,59.9722,24.8275,35.1448,11.4549,5.8324,2.1079,-4.8168,621.8020
751,-1,213.2414,79.4822,2,2,2,3,11,11,0,...,0,5,37.6667,14.6367,23.0300,0.0000,2.7735,1.1977,-4.3289,431.0078
752,-1,136.1962,41.8416,1,3,2,0,12,8,0,...,0,2,21.1667,13.4241,7.7425,0.0000,2.9258,0.8819,-4.2870,336.1327
753,-1,350.3886,113.2147,3,5,2,5,18,16,5,...,1,8,64.2500,8.5070,55.7430,0.0000,4.2674,1.7984,-4.5739,572.9925

In [14]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [15]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [16]:
print(X_train_scaled.shape)
print(X_test_scaled.shape)

(603, 139)
(151, 139)